export const MemberModel = {
  id: null,
  //address: null,
  //balance: null,
  //createDate: null,
  //description: null,
  email: null,
  password: null,
  telephone: null,
  //point: null,
  sex: null,
  //state: null,
  //modifyDate: null,
  username: null,
  //remark: null,
};